# Generated by Django 5.0 on 2026-01-31 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Formación académica',
                'verbose_name_plural': 'Formación académica',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(default='2023-12-31')),
                ('fecha_fin', models.DateField(default='2024-01-01')),
                ('description', models.TextField()),
                ('url_demo', models.URLField(blank=True, null=True)),
                ('url_repo', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('tools', 'Herramientas')], max_length=20)),
                ('icon', models.CharField(default='⚙️', max_length=10)),
            ],
            options={
                'verbose_name': 'Información General',
                'verbose_name_plural': 'Información General',
                'ordering': ['category', 'name'],
            },
        ),
    ]
