# Generated by Django 5.0 on 2026-02-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=120)),
                ('empresa', models.CharField(max_length=120)),
                ('fecha_inicio', models.CharField(max_length=30)),
                ('fecha_fin', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', '-id'],
            },
        ),
    ]
