# Generated by Django 6.0.1 on 2026-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['orden', '-date']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['orden', '-date'], 'verbose_name': 'Formación académica', 'verbose_name_plural': 'Formación académica'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['orden', '-id'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['orden', '-fecha_fin'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolio'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'orden', 'name'], 'verbose_name': 'Información General', 'verbose_name_plural': 'Información General'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
