# Generated by Django 5.0 on 2026-01-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_education_project_skill_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('plataforma', models.CharField(blank=True, max_length=200)),
                ('enlace', models.URLField()),
                ('fecha_obtencion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_obtencion'],
            },
        ),
    ]
