# Generated by Django 5.0 on 2026-01-28 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_certificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_obtencion'], 'verbose_name': 'Certificados', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-date'], 'verbose_name': 'Formación académica', 'verbose_name_plural': 'Formación académica'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolio'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Información General', 'verbose_name_plural': 'Información General'},
        ),
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='portafolios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
