# Generated by Django 6.0.1 on 2026-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_certificado_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('nativo', 'Nativo'), ('c2', 'C2 - Dominio'), ('c1', 'C1 - Avanzado'), ('b2', 'B2 - Intermedio Alto'), ('b1', 'B1 - Intermedio'), ('a2', 'A2 - Básico'), ('a1', 'A1 - Principiante')], max_length=20)),
                ('descripcion_nivel', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
