# Generated by Django 6.0.1 on 2026-02-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_idioma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Información General', 'verbose_name_plural': 'Información General'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('code', 'HTML / Código'), ('palette', 'CSS / Diseño'), ('zap', 'JavaScript'), ('file-code', 'TypeScript'), ('terminal', 'Python'), ('globe', 'Django'), ('git-branch', 'Git'), ('github', 'GitHub'), ('database', 'Base de datos'), ('server', 'Backend / Server')], default='code', max_length=50),
        ),
    ]
